config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^', include('jemlokalnie.website.urls', namespace='website')),
    # url(r'^dolacz/wyslane/$', TemplateView.as_view(template_name='contact_form/contact_form_sent.html'),name='contact_form_sent'),
    url(r'^dolacz/', include('contact_form.urls', namespace='dolacz')),
    url(r'^stowarzyszenie/$', RedirectView.as_view(url='http://jemlokalnie.org'), name='about'),
    
    url(settings.ADMIN_URL, admin.site.urls),

    url(r'^czlonkowie/', include('jemlokalnie.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

jemlokalnie/users/urls.py
from django.conf.urls import url

from . import views

# usermatch = "[\w.@+-]+"
usermatch = ".+"
urlpatterns = [
    url(
        regex=r'^umowa/(?P<username>{})/$'.format(usermatch),
        view=views.UserListViewDeal.as_view(),
        name='umowa'
    ),
    url(
        regex=r'^qr/(?P<username>{})/$'.format(usermatch),
        view=views.UserListViewQR.as_view(),
        name='qr'
    ),
    url(
        regex=r'^polecwytworce/(?P<username>{})/$'.format(usermatch),
        view=views.UserAddProviderDistributor.as_view(),
        name='polecwytworce'
    ),
    url(
        regex=r'^polecrestautacje/(?P<username>{})/$'.format(usermatch),
        view=views.UserAddProviderDistributor.as_view(),
        name='polecrestautacje'
    ),
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>{})/$'.format(usermatch),
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

# [\w.@+- ]

jemlokalnie/website/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from allauth.account.views import SignupView
from . import views

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='website/home_intro.html'), name='home'),
    url(r'^$', views.HomeView.as_view(), name='home'),
    # url(r'^dolacz$', TemplateView.as_view(template_name='website/signup_intro.html'), name='signup_intro'),
    url(r'^dolacz$', SignupView.as_view(), name='signup_intro'),
    url(r'^dolacz/$', SignupView.as_view(), name='contact_form'),
    url(r'^onas$', TemplateView.as_view(template_name='website/home_about.html'), name='about'),
    url(r'^restauracje$', views.FoodDistributorsView.as_view(), name='restauracje'),
    url(r'^sklepy$', views.FoodDistributorsShopView.as_view(), name='sklepy'),
    url(r'^wytworcy$', views.FoodProvidersView.as_view(), name='producenci'),
    url(
        regex=r'^wytworcy/(?P<name>[\w.@+-]+)/$',
        view=views.FoodProviderView.as_view(),
        name='producent'
    ),
    url(
        regex=r'^restauracje/(?P<name>[\w.@+-]+)/$',
        view=views.FoodDistributorView.as_view(),
        name='restauracja'
    ),
    url(
        regex=r'^sklepy/(?P<name>[\w.@+-]+)/$',
        view=views.FoodDistributorShopView.as_view(),
        name='sklep'
    ),
]

jemlokalnie/models.py
import logging, sys, datetime, dateutil.parser

from django.conf import settings
from django.db import models
from django.db.models import Q,F,Count, signals
from django.db.models.query import QuerySet
from django.forms.models import model_to_dict
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned

from django.contrib.auth.models import User, Group, Permission
from django.contrib.contenttypes.models import ContentType

from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse, reverse_lazy


logger = logging.getLogger( settings.DEFAULT_LOGGER )

jemlokalnie/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from itertools import chain
import logging

from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView
from django.forms.models import inlineformset_factory
from django import forms
from django.core.exceptions import SuspiciousOperation

from django.contrib.auth.mixins import LoginRequiredMixin

from django.utils.translation import ugettext_lazy as _

from .models import User
from jemlokalnie.engine.models import FoodDistributor, FoodProvider, FoodDistributorShop, \
                                      FoodImgDistr, FoodImgProvider, FoodImgDistrShop

from pprint import pprint as pp

logger = logging.getLogger(settings.DEFAULT_LOGGER)

FoodDistributorFormSet      = inlineformset_factory(User, FoodDistributor, extra=0, can_delete = False, 
                                fields = ["name","tags","adress","location","short","long"])
FoodProviderFormSet         = inlineformset_factory(User, FoodProvider, extra=0, can_delete = False, 
                                fields = ["name","tags","adress","location","short","long"])
FoodDistributorShopFormSet  = inlineformset_factory(User, FoodDistributorShop, extra=0, can_delete = False, 
                                fields = ["name","tags","adress","location","short","long"])

FoodProviderImgFormSet  = inlineformset_factory(FoodProvider, FoodImgProvider, extra=1, can_delete = True, fields = ["img_f",])
FoodDistrImgFormSet     = inlineformset_factory(FoodDistributor, FoodImgDistr, extra=1, can_delete = True, fields = ["img_f",])
FoodDistrShopImgFormSet = inlineformset_factory(FoodDistributorShop, FoodImgDistrShop, extra=1, can_delete = True, fields = ["img_f",])

class UserDetailFomMixin(object):
    def add_user_type_formset(self, context):
        context['user_type']  = dict(User.TYPES)[self.object.user_type];
        if self.request.POST:
            if self.object.user_type in (User.TYPES_FD, ):
                context['fd_form']  = FoodDistributorFormSet(self.request.POST, instance=self.object)
                context['fd_iform'] = FoodDistrImgFormSet(self.request.POST, self.request.FILES, instance=self.object.fooddistributor_set.first())
            if self.object.user_type in (User.TYPES_FP, ):
                context['fp_form']  = FoodProviderFormSet(self.request.POST, instance=self.object)
                context['fp_iform'] = FoodProviderImgFormSet(self.request.POST, self.request.FILES, instance=self.object.foodprovider_set.first())
            if self.object.user_type in (User.TYPES_FDS, ):
                context['fs_form']  = FoodDistributorShopFormSet(self.request.POST, instance=self.object)
                context['fs_iform'] = FoodDistrShopImgFormSet(self.request.POST, self.request.FILES, instance=self.object.fooddistributorshop_set.first())
        else:
            if self.object.user_type in (User.TYPES_FD, ):
                context['fd_form']  = FoodDistributorFormSet(instance=self.object)
                context['fd_iform'] = FoodDistrImgFormSet(instance=self.object.fooddistributor_set.first())
            if self.object.user_type in (User.TYPES_FP, ):
                context['fp_form']  = FoodProviderFormSet(instance=self.object)
                context['fp_iform'] = FoodProviderImgFormSet(instance=self.object.foodprovider_set.first())
            if self.object.user_type in (User.TYPES_FDS, ):
                context['fs_form']  = FoodDistributorShopFormSet(instance=self.object)
                context['fs_iform'] = FoodDistrShopImgFormSet(instance=self.object.fooddistributorshop_set.first())
        return context

class UserDetailView(LoginRequiredMixin, UserDetailFomMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data( self, **kwargs):
        context = super( UserDetailView, self).get_context_data(**kwargs)

        self.add_user_type_formset(context)
        context['phone'] = self.object.phone;

        context['my_sites'] = []
        for obj in chain(self.object.foodprovider_set.all(),
                         self.object.fooddistributor_set.all(),
                         self.object.fooddistributorshop_set.all()):
            context['my_sites'].append(obj.url)
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})



class UserUpdateView(LoginRequiredMixin, UserDetailFomMixin, UpdateView):
    fields = ['phone']
    model = User

    def get_success_url(self):
        return reverse('users:detail', kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)

    def get_context_data( self, **kwargs):
        context = super( UserUpdateView, self).get_context_data(**kwargs)
        self.add_user_type_formset(context)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        inline_forms = [(x,context[x]) for x in ['fp_form','fd_form','fs_form','fp_iform','fd_iform','fs_iform'] if x in context]
        logger.debug(inline_forms)

        if all(x[1].is_valid() for x in inline_forms ):
            self.object = form.save()
            for x in inline_forms:
                if x[0] == 'fp_iform':
                    x[1].instance = self.object.foodprovider_set.first()
                elif x[0] == 'fd_iform':
                    x[1].instance = self.object.fooddistributor_set.first()
                elif x[0] == 'fs_iform':
                    x[1].instance = self.object.fooddistributorshop_set.first()
                else:
                    x[1].instance = self.object
                x[1].save()
            return super(UserUpdateView, self).form_valid(form)

        return self.render_to_response(self.get_context_data(form=form))

class UserListViewDeal(LoginRequiredMixin, UserDetailFomMixin, DetailView):
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name = "users/deal_1.html"

    def get_context_data( self, **kwargs):
        context = super( DetailView, self).get_context_data(**kwargs)
        if self.request.user.username != context['user'].username and not self.request.user.is_staff:
            raise SuspiciousOperation("Przykro nam ale ta strone nie jest dla Państwa dostępna. Incydent został zalogowany")

        return context

class UserListViewQR(LoginRequiredMixin, UserDetailFomMixin, DetailView):
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name = "users/qr.html"

    def get_context_data( self, **kwargs):
        context = super( DetailView, self).get_context_data(**kwargs)

        self.add_user_type_formset(context)
        context['phone'] = self.object.phone;

        context['my_sites'] = []
        for obj in chain(self.object.foodprovider_set.all(),
                         self.object.fooddistributor_set.all(),
                         self.object.fooddistributorshop_set.all()):
            context['my_sites'].append(obj.url)

        context['contact'] = self.object.contact
        return context

class UserListView(LoginRequiredMixin, ListView):
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'

class UserAddProviderDistributor(UserDetailView):
    template_name = "users/user_add_more.html"
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'

class JemlokalnieSignupForm( forms.Form ):
    user_type = forms.ChoiceField( choices = User.TYPES, label=_('Rodzaj aktywności'))
    rules_accepted =  forms.BooleanField( label=_('Akceptuję regulamin oraz zasady ochrony danych osobowych (RODO)'), required = True )
    deal_accepted =  forms.BooleanField( label=_('Potwierdzam zawarcie umowy'), required = False )
    full_name = forms.CharField( label=_('Imię i nazwisko'), required = True ,help_text="Imię i nazwisko lub nazwa firmy.")
    tax_id = forms.CharField( label=_('NIP/PESEL'), required = False ,help_text="Podaj jeżeli chcesz przystąpić do programu JemLokalnie.")
    phisical_address = forms.CharField( label=_('Adres korespondencyjny'), required = False,help_text="Podaj jeżeli chcesz przystąpić do programu JemLokalnie")
    phone = forms.CharField( label=_('Numer telefonu'), required = False )

    def clean_rules_accepted(self):
        data = self.cleaned_data['rules_accepted']

        if not data:
            raise forms.ValidationError("Proszę zaakceptować regulamin i potwierdzić zapoznanie się z RODO")
        return data

    def clean_deal_accepted(self):
        data = self.cleaned_data['deal_accepted']
        active_user_type = self.cleaned_data['user_type'] != '4'

        if active_user_type and not data:
            raise forms.ValidationError("Proszę zaakceptować umowę")
        return data

    def clean_tax_id(self):
        data = self.cleaned_data['tax_id']
        active_user_type = self.cleaned_data['user_type'] != '4'

        if active_user_type:
            if not data:
                raise forms.ValidationError("Dla zaznaczonego rodzaju aktywności w Programie to pole jest wymagane.")
            if len(data) < 7:
                raise forms.ValidationError("Proszę wpisz więcej.")
        return data

    def clean_phisical_address(self):
        data = self.cleaned_data['phisical_address']
        active_user_type = self.cleaned_data['user_type'] != '4'
        
        if active_user_type:
            if not data:
                raise forms.ValidationError("Dla zaznaczonego rodzaju aktywności w Programie to pole jest wymagane.")

jemlokalnie/website/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import logging

from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView
from django.forms.models import inlineformset_factory
from django import forms

from django.contrib.auth.mixins import LoginRequiredMixin

from django.utils.translation import ugettext_lazy as _

from jemlokalnie.engine.models import FoodDistributor, FoodProvider, FoodDistributorShop

logger = logging.getLogger(settings.DEFAULT_LOGGER)

class FoodProviderView( DetailView):
    model = FoodProvider
    slug_field = 'slug'
    slug_url_kwarg = 'name'
    template_name = "website/foodprovider.html" 

    def get_context_data( self, **kwargs):
        context = super( DetailView, self).get_context_data(**kwargs)
        context['images'] = context['object'].images
        context['contact'] = self.object.contact
        return context

class FoodProvidersView( ListView ):
    model = FoodProvider
    template_name = "website/foodprovider_list.html"

    def get_context_data( self, **kwargs):
        context = super( ListView, self).get_context_data(**kwargs)
        context['the_name'] = self.model._meta.verbose_name_plural
        context['object_list'] = filter(lambda x: x.ready, context['object_list'])
        return context


class FoodDistributorView( FoodProviderView):
    model = FoodDistributor

class FoodDistributorsView( FoodProvidersView ):
    model = FoodDistributor
    template_name = "website/foodprovider_list.html"	


class FoodDistributorShopView( FoodProviderView):
    model = FoodDistributorShop

class FoodDistributorsShopView( FoodProvidersView ):
    model = FoodDistributorShop
    template_name = "website/foodprovider_list.html"


class HomeView(TemplateView):
    template_name = "website/home.html"

    def get_context_data( self, **kwargs):
        context = super( HomeView, self).get_context_data(**kwargs)
        context['object_list']=[]
        context['object_list']+=FoodDistributor.objects.all();
        context['object_list']+=FoodDistributorShop.objects.all();
        context['object_list']+=FoodProvider.objects.all();

        context['object_list'] = filter(lambda x: x.ready, context['object_list'])
        return context  

jemlokalnie/templates/users/_users_links.html
<a class="btn btn-primary" href="{% url 'users:detail' username=object.username  %}" role="button">Moje konto</a>&nbsp;&nbsp;&nbsp; 
<a class="btn btn-primary" href="{% url 'users:update' %}" role="button">Zmień informacje</a>&nbsp;&nbsp;&nbsp; 
<!--a class="btn btn-primary" href="{% url 'account_email' %}" role="button">Moje adresy E-Mail</a-->
<a class="btn btn-primary" href="{% url 'users:polecwytworce' username=object.username %}" role="button">Zgłoś Wytwórcę</a>
<a class="btn btn-primary" href="{% url 'users:polecrestautacje' username=object.username  %}" role="button">Zgłoś Sklep | Restaurację</a>
<br><br>
{% for site_url in my_sites %}
<a class="btn btn-primary" target='_blank' href="{{site_url}}" role="button">Moja strona</a>&nbsp;&nbsp;&nbsp; 
<a class="btn btn-primary" target='_blank' href="{% url 'users:umowa' username=object.username  %}" role="button">Moja umowa</a>&nbsp; 
<a class="btn btn-primary" href="{% url 'users:qr' username=object.username  %}" role="button">QR kod</a>
{% endfor %}

jemlokalnie/templates/users/qr.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load qr_tags %}

{% block title %}QR kod: {{ object.username }}{% endblock %}
{% block content %}


<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="d-inline">{{ object.username }}</h1> <h2 class="d-inline"> ( {{ user_type }} )</h2><h1></h1>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

<div class="row">
<div class="col-sm-12">
{% include "users/_users_links.html" %}
</div>
</div>
<br><br><br><br>
<div style='float: left'>
{% qr_from_text contact.url 500 %}
{% qr_from_text contact.url 230 %} 
{% qr_from_text contact.url 100 %}
</div>
</div>
{% endblock content %}

jemlokalnie/templates/users/user_add_more.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans "User" %}: {{ object.username }}{% endblock %}
{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      
      <h1 class="d-inline">{{ object.username }}</h1> <h2 class="d-inline"> ( {{ user_type }} )</h2><h1></h1>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

<div class="row">
<div class="col-sm-12">
{% include "users/_users_links.html" %}
</div>
<br><br><br><br><br>
<h2>
 Jeżeli uważasz że znasz godnego polecenia wytwórcę żywności, sklep lub restaurację napisz do nas na adres <a href="mailto:biuro@jemlokalnie.org">biuro@jemlokalnie.org</a> a skontaktujemy się znim aby zaprosić go do Jemlokalnie.org.<br><br>Z góry dziękukjemy<br>
 Zespół Jemlokalnie.org<br>
</h2>
</div>

</div>
{% endblock content %}

jemlokalnie/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans "User" %}: {{ object.username }}{% endblock %}
{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      
      <h1 class="d-inline">{{ object.username }}</h1> <h2 class="d-inline"> ( {{ user_type }} )</h2><h1></h1>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>
{% if object == request.user %}
<div class="row">
<div class="col-sm-12">
{% include "users/_users_links.html" %}
</div>
<br><br><br><br>
<div class="col-sm-12"> 
    <style>
    label,small {display:none;}
    input, textarea 
    { 
      border:0 !important; 
      font-size:35px !important;
      font-weight: 600;
      font-family: Amatic SC !important;
      color: black !important;
      box-shadow: none !important;
    }
    </style>
    <formset disabled="disabled" >
    {% include "../website/_form_img.html" with form=fd_iform %}
    {% include "../website/_form_plain.html" with form=fd_form %}
    {% include "../website/_form_img.html" with form=fp_iform %}
    {% include "../website/_form_plain.html" with form=fp_form %}
    {% include "../website/_form_img.html" with form=fs_iform %}
    {% include "../website/_form_plain.html" with form=fs_form %}
    </formset>   
</div>
<style type="text/css">
  .normall
  {
    cursor:default !important;
    background-color: white !important;
  }
</style>
<script type="text/javascript">
  $('formset').find('input, textarea').attr('readonly','readonly').addClass('normall');
  $("input").each(function(){
    if($(this).attr('class') && $(this).attr('class').indexOf("tagwidget") != -1) 
    {
        var i;
        var stuff = ['name','id','class','style','readonly'];
        var attrs = "";
        for (i = 0; i < stuff.length; i++) 
        { 
            if($(this).attr(stuff[i]))
            {
                attrs+=stuff[i]+"='"+$(this).attr(stuff[i])+"' ";
            }
        }
        value = ''
        if($(this).attr('value'))
        {
            value = $(this).attr('value');
        }
        $(this).replaceWith("<textarea "+attrs+">"+value+"</textarea>");
      }
});
</script>

</div>
{% endif %}
</div>
{% endblock content %}

jemlokalnie/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1 class="d-inline">{{ user.username }}</h1> <h2 class="d-inline"> ( {{ user_type }} )</h2><h1></h1>
<div class="row">
<div class="col-sm-12">
{% include "users/_users_links.html" %}
</div>
</div><br><br>
  <form class="form-horizontal" action="{% url 'users:update' %}" method="post" 
  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    {{ fd_form.media }}
    {{ fd_form|crispy}}
    {{ fd_iform.media }}
    {{ fd_iform|crispy}}
    {{ fp_form.media }}
    {{ fp_form|crispy}}
    {{ fp_iform.media }}
    {{ fp_iform|crispy}}
    {{ fs_form.media }}
    {{ fs_form|crispy}}
    {{ fs_iform.media }}
    {{ fs_iform|crispy}}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
        <br><br>
      </div>
    </div>
  </form> 
<script>
  $("input").each(function(){
    if($(this).attr('class') && $(this).attr('class').indexOf("tagwidget") != -1) 
    {
        var i;
        var stuff = ['name','id','class','style','readonly'];
        var attrs = "";
        for (i = 0; i < stuff.length; i++) 
        { 
            if($(this).attr(stuff[i]))
            {
                attrs+=stuff[i]+"='"+$(this).attr(stuff[i])+"' ";
            }
        }
        value = ''
        if($(this).attr('value'))
        {
            value = $(this).attr('value');
        }
        $(this).replaceWith("<textarea "+attrs+">"+value+"</textarea>");
      }
});
</script>
{% endblock %}

jemlokalnie/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}