config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^', include('jemlokalnie.website.urls', namespace='website')),
    # url(r'^dolacz/wyslane/$', TemplateView.as_view(template_name='contact_form/contact_form_sent.html'),name='contact_form_sent'),
    url(r'^dolacz/', include('contact_form.urls', namespace='dolacz')),
    url(r'^stowarzyszenie/$', RedirectView.as_view(url='http://jemlokalnie.org'), name='about'),
    
    url(settings.ADMIN_URL, admin.site.urls),

    url(r'^czlonkowie/', include('jemlokalnie.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

jemlokalnie/users/urls.py
from django.conf.urls import url

from . import views

# usermatch = "[\w.@+-]+"
usermatch = ".+"
urlpatterns = [
    url(
        regex=r'^umowa/(?P<username>{})/$'.format(usermatch),
        view=views.UserListViewDeal.as_view(),
        name='umowa'
    ),
    url(
        regex=r'^qr/(?P<username>{})/$'.format(usermatch),
        view=views.UserListViewQR.as_view(),
        name='qr'
    ),
    url(
        regex=r'^polecwytworce/(?P<username>{})/$'.format(usermatch),
        view=views.UserAddProviderDistributor.as_view(),
        name='polecwytworce'
    ),
    url(
        regex=r'^polecrestautacje/(?P<username>{})/$'.format(usermatch),
        view=views.UserAddProviderDistributor.as_view(),
        name='polecrestautacje'
    ),
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>{})/$'.format(usermatch),
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

# [\w.@+- ]

jemlokalnie/website/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from allauth.account.views import SignupView
from . import views

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='website/home_intro.html'), name='home'),
    url(r'^$', views.HomeView.as_view(), name='home'),
    # url(r'^dolacz$', TemplateView.as_view(template_name='website/signup_intro.html'), name='signup_intro'),
    url(r'^dolacz$', SignupView.as_view(), name='signup_intro'),
    url(r'^dolacz/$', SignupView.as_view(), name='contact_form'),
    url(r'^onas$', TemplateView.as_view(template_name='website/home_about.html'), name='about'),
    url(r'^restauracje$', views.FoodDistributorsView.as_view(), name='restauracje'),
    url(r'^sklepy$', views.FoodDistributorsShopView.as_view(), name='sklepy'),
    url(r'^wytworcy$', views.FoodProvidersView.as_view(), name='producenci'),
    url(
        regex=r'^wytworcy/(?P<name>[\w.@+-]+)/$',
        view=views.FoodProviderView.as_view(),
        name='producent'
    ),
    url(
        regex=r'^restauracje/(?P<name>[\w.@+-]+)/$',
        view=views.FoodDistributorView.as_view(),
        name='restauracja'
    ),
    url(
        regex=r'^sklepy/(?P<name>[\w.@+-]+)/$',
        view=views.FoodDistributorShopView.as_view(),
        name='sklep'
    ),
]

jemlokalnie/models.py
import logging, sys, datetime, dateutil.parser

from django.conf import settings
from django.db import models
from django.db.models import Q,F,Count, signals
from django.db.models.query import QuerySet
from django.forms.models import model_to_dict
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned

from django.contrib.auth.models import User, Group, Permission
from django.contrib.contenttypes.models import ContentType

from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse, reverse_lazy


logger = logging.getLogger( settings.DEFAULT_LOGGER )

jemlokalnie/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from itertools import chain
import logging

from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView
from django.forms.models import inlineformset_factory
from django import forms
from django.core.exceptions import SuspiciousOperation

from django.contrib.auth.mixins import LoginRequiredMixin

from django.utils.translation import ugettext_lazy as _

from .models import User
from jemlokalnie.engine.models import FoodDistributor, FoodProvider, FoodDistributorShop, \
                                      FoodImgDistr, FoodImgProvider, FoodImgDistrShop

from pprint import pprint as pp

logger = logging.getLogger(settings.DEFAULT_LOGGER)

FoodDistributorFormSet      = inlineformset_factory(User, FoodDistributor, extra=0, can_delete = False, 
                                fields = ["name","tags","adress","location","short","long"])
FoodProviderFormSet         = inlineformset_factory(User, FoodProvider, extra=0, can_delete = False, 
                                fields = ["name","tags","adress","location","short","long"])
FoodDistributorShopFormSet  = inlineformset_factory(User, FoodDistributorShop, extra=0, can_delete = False, 
                                fields = ["name","tags","adress","location","short","long"])

FoodProviderImgFormSet  = inlineformset_factory(FoodProvider, FoodImgProvider, extra=1, can_delete = True, fields = ["img_f",])
FoodDistrImgFormSet     = inlineformset_factory(FoodDistributor, FoodImgDistr, extra=1, can_delete = True, fields = ["img_f",])
FoodDistrShopImgFormSet = inlineformset_factory(FoodDistributorShop, FoodImgDistrShop, extra=1, can_delete = True, fields = ["img_f",])

class UserDetailFomMixin(object):
    def add_user_type_formset(self, context):
        context['user_type']  = dict(User.TYPES)[self.object.user_type];
        if self.request.POST:
            if self.object.user_type in (User.TYPES_FD, ):
                context['fd_form']  = FoodDistributorFormSet(self.request.POST, instance=self.object)
                context['fd_iform'] = FoodDistrImgFormSet(self.request.POST, self.request.FILES, instance=self.object.fooddistributor_set.first())
            if self.object.user_type in (User.TYPES_FP, ):
                context['fp_form']  = FoodProviderFormSet(self.request.POST, instance=self.object)
                context['fp_iform'] = FoodProviderImgFormSet(self.request.POST, self.request.FILES, instance=self.object.foodprovider_set.first())
            if self.object.user_type in (User.TYPES_FDS, ):
                context['fs_form']  = FoodDistributorShopFormSet(self.request.POST, instance=self.object)
                context['fs_iform'] = FoodDistrShopImgFormSet(self.request.POST, self.request.FILES, instance=self.object.fooddistributorshop_set.first())
        else:
            if self.object.user_type in (User.TYPES_FD, ):
                context['fd_form']  = FoodDistributorFormSet(instance=self.object)
                context['fd_iform'] = FoodDistrImgFormSet(instance=self.object.fooddistributor_set.first())
            if self.object.user_type in (User.TYPES_FP, ):
                context['fp_form']  = FoodProviderFormSet(instance=self.object)
                context['fp_iform'] = FoodProviderImgFormSet(instance=self.object.foodprovider_set.first())
            if self.object.user_type in (User.TYPES_FDS, ):
                context['fs_form']  = FoodDistributorShopFormSet(instance=self.object)
                context['fs_iform'] = FoodDistrShopImgFormSet(instance=self.object.fooddistributorshop_set.first())
        return context

class UserDetailView(LoginRequiredMixin, UserDetailFomMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data( self, **kwargs):
        context = super( UserDetailView, self).get_context_data(**kwargs)

        self.add_user_type_formset(context)
        context['phone'] = self.object.phone;

        context['my_sites'] = []
        for obj in chain(self.object.foodprovider_set.all(),
                         self.object.fooddistributor_set.all(),
                         self.object.fooddistributorshop_set.all()):
            context['my_sites'].append(obj.url)
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})



class UserUpdateView(LoginRequiredMixin, UserDetailFomMixin, UpdateView):
    fields = ['phone']
    model = User

    def get_success_url(self):
        return reverse('users:detail', kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)

    def get_context_data( self, **kwargs):
        context = super( UserUpdateView, self).get_context_data(**kwargs)
        self.add_user_type_formset(context)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        inline_forms = [(x,context[x]) for x in ['fp_form','fd_form','fs_form','fp_iform','fd_iform','fs_iform'] if x in context]
        logger.debug(inline_forms)

        if all(x[1].is_valid() for x in inline_forms ):
            self.object = form.save()
            for x in inline_forms:
                if x[0] == 'fp_iform':
                    x[1].instance = self.object.foodprovider_set.first()
                elif x[0] == 'fd_iform':
                    x[1].instance = self.object.fooddistributor_set.first()
                elif x[0] == 'fs_iform':
                    x[1].instance = self.object.fooddistributorshop_set.first()
                else:
                    x[1].instance = self.object
                x[1].save()
            return super(UserUpdateView, self).form_valid(form)

        return self.render_to_response(self.get_context_data(form=form))

class UserListViewDeal(LoginRequiredMixin, UserDetailFomMixin, DetailView):
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name = "users/deal_1.html"

    def get_context_data( self, **kwargs):
        context = super( DetailView, self).get_context_data(**kwargs)
        if self.request.user.username != context['user'].username and not self.request.user.is_staff:
            raise SuspiciousOperation("Przykro nam ale ta strone nie jest dla Państwa dostępna. Incydent został zalogowany")

        return context

class UserListViewQR(LoginRequiredMixin, UserDetailFomMixin, DetailView):
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name = "users/qr.html"

    def get_context_data( self, **kwargs):
        context = super( DetailView, self).get_context_data(**kwargs)

        self.add_user_type_formset(context)
        context['phone'] = self.object.phone;

        context['my_sites'] = []
        for obj in chain(self.object.foodprovider_set.all(),
                         self.object.fooddistributor_set.all(),
                         self.object.fooddistributorshop_set.all()):
            context['my_sites'].append(obj.url)

        context['contact'] = self.object.contact
        return context

class UserListView(LoginRequiredMixin, ListView):
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'

class UserAddProviderDistributor(UserDetailView):
    template_name = "users/user_add_more.html"
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'

class JemlokalnieSignupForm( forms.Form ):
    user_type = forms.ChoiceField( choices = User.TYPES, label=_('Rodzaj aktywności'))
    rules_accepted =  forms.BooleanField( label=_('Akceptuję regulamin oraz zasady ochrony danych osobowych (RODO)'), required = True )
    deal_accepted =  forms.BooleanField( label=_('Potwierdzam zawarcie umowy'), required = False )
    full_name = forms.CharField( label=_('Imię i nazwisko'), required = True ,help_text="Imię i nazwisko lub nazwa firmy.")
    tax_id = forms.CharField( label=_('NIP/PESEL'), required = False ,help_text="Podaj jeżeli chcesz przystąpić do programu JemLokalnie.")
    phisical_address = forms.CharField( label=_('Adres korespondencyjny'), required = False,help_text="Podaj jeżeli chcesz przystąpić do programu JemLokalnie")
    phone = forms.CharField( label=_('Numer telefonu'), required = False )

    def clean_rules_accepted(self):
        data = self.cleaned_data['rules_accepted']

        if not data:
            raise forms.ValidationError("Proszę zaakceptować regulamin i potwierdzić zapoznanie się z RODO")
        return data

    def clean_deal_accepted(self):
        data = self.cleaned_data['deal_accepted']
        active_user_type = self.cleaned_data['user_type'] != '4'

        if active_user_type and not data:
            raise forms.ValidationError("Proszę zaakceptować umowę")
        return data

    def clean_tax_id(self):
        data = self.cleaned_data['tax_id']
        active_user_type = self.cleaned_data['user_type'] != '4'

        if active_user_type:
            if not data:
                raise forms.ValidationError("Dla zaznaczonego rodzaju aktywności w Programie to pole jest wymagane.")
            if len(data) < 7:
                raise forms.ValidationError("Proszę wpisz więcej.")
        return data

    def clean_phisical_address(self):
        data = self.cleaned_data['phisical_address']
        active_user_type = self.cleaned_data['user_type'] != '4'
        
        if active_user_type:
            if not data:
                raise forms.ValidationError("Dla zaznaczonego rodzaju aktywności w Programie to pole jest wymagane.")

jemlokalnie/website/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import logging

from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, TemplateView
from django.forms.models import inlineformset_factory
from django import forms

from django.contrib.auth.mixins import LoginRequiredMixin

from django.utils.translation import ugettext_lazy as _

from jemlokalnie.engine.models import FoodDistributor, FoodProvider, FoodDistributorShop

logger = logging.getLogger(settings.DEFAULT_LOGGER)

class FoodProviderView( DetailView):
    model = FoodProvider
    slug_field = 'slug'
    slug_url_kwarg = 'name'
    template_name = "website/foodprovider.html" 

    def get_context_data( self, **kwargs):
        context = super( DetailView, self).get_context_data(**kwargs)
        context['images'] = context['object'].images
        context['contact'] = self.object.contact
        return context

class FoodProvidersView( ListView ):
    model = FoodProvider
    template_name = "website/foodprovider_list.html"

    def get_context_data( self, **kwargs):
        context = super( ListView, self).get_context_data(**kwargs)
        context['the_name'] = self.model._meta.verbose_name_plural
        context['object_list'] = filter(lambda x: x.ready, context['object_list'])
        return context


class FoodDistributorView( FoodProviderView):
    model = FoodDistributor

class FoodDistributorsView( FoodProvidersView ):
    model = FoodDistributor
    template_name = "website/foodprovider_list.html"	


class FoodDistributorShopView( FoodProviderView):
    model = FoodDistributorShop

class FoodDistributorsShopView( FoodProvidersView ):
    model = FoodDistributorShop
    template_name = "website/foodprovider_list.html"


class HomeView(TemplateView):
    template_name = "website/home.html"

    def get_context_data( self, **kwargs):
        context = super( HomeView, self).get_context_data(**kwargs)
        context['object_list']=[]
        context['object_list']+=FoodDistributor.objects.all();
        context['object_list']+=FoodDistributorShop.objects.all();
        context['object_list']+=FoodProvider.objects.all();

        context['object_list'] = filter(lambda x: x.ready, context['object_list'])
        return context  

jemlokalnie/templates/403_csrf.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}403{% endblock %}
{% block banner %}
<center>
<p class="h2">
Prawdopodobnie upłynęło już trochę czasu między tym kiedy odwiedziłeś naszą stronę a chwilą kiedy odsyłasz nam formularz. [CRSF, 403]<br><br> 
</center>
<a href="/" ><img src="{% static 'images/landing.jpg' %}" class='baner-landing'></a>
{% endblock banner %}
{% block content %}

{% endblock content %}

jemlokalnie/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
{% load leaflet_tags %}
<html lang="en"><head><meta charset="utf-8">
    <link rel="icon" href="/static/images/favico.ico" type="image/x-icon" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Jemlokalnie {% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="www.pawellukaszewicz.com">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    {% block css %}
    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous"-->
    <dlink rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Amatic+SC:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/project.css' %}?20190426" rel="stylesheet">
    <style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans:400,600&subset=latin-ext');
    </style>

    {% leaflet_css %}
    {% endblock %}

    {% block javascript %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-116210728-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-116210728-1');
    </script>
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
      <script src="{% static 'js/project.js' %}"></script>
      <script src="{% static 'js/imageMapResizer.min.js' %}"></script>
    {% leaflet_js %}
    {% endblock javascript %}
  </head>
  <body><div class="m-b-1">
<nav class="navbar navbar-default bg-faded navbar-static-top"> 
      <div class="container"> 
        <div class="navbar-header"> 
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-8" aria-expanded="false"> 
            <span class="icon-bar"></span> 
            <span class="icon-bar"></span> 
            <span class="icon-bar"></span> 
          </button> 
          
            <a class="navbar-brand" href="{% url 'website:home' %}"><h1 style='margin-top:-10px !important'>jemlokalnie.org</h1> <div class='logo'></div></a>
        </div> 
        <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-8" aria-expanded="false" style="height: 1px;"> 
          <ul class="nav navbar-nav"> 
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:about' %}">O Nas</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:producenci' %}">Producenci</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:restauracje' %}">Restauracje</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:sklepy' %}">Sklepy</a>
                  </li>
                  {% if request.user.is_authenticated %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "Moje konto" %}</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                      <a id="sign-up-link" class="nav-link" style='color:#45b648 !important' href="{% url 'dolacz:contact_form' %}">{% trans "Dołącz" %}</a>
                  </li>
                  <!--li class="nav-item">
                      <a id="log-in-link" class="nav-link" href="url 'dolacz:contact_form' #dolacz">{% trans "Dołącz" %}</a>
                  </li-->
                  <li class="nav-item">
                      <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                  </li>
                  {% endif %}

          </ul> 
        </div> 
       </div> 
</nav>
</div>
<div class='baner-landing'>
{% block banner %}
{% endblock banner %}
</div>
    <div class="container">
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        
      {% endblock content %}
    </div> <!-- /container -->
  {% block content2 %}
  {% endblock content2 %}
   <div class="container">
      {% block content3 %}
        
      {% endblock content3 %}
    </div> <!-- /container -->
      <footer class="footer">
          <div class="container">
              <div class="col-md-3 col-sm-6 col-xs-12 text-muted sep-small">Skontaktuj się z nami:</div>
              <div class="col-md-3 col-sm-6 col-xs-12 text-muted sep-small">
                  <a href="tel:+48 536 760 295">+48 536 760 295</a>
              </div>
              <div class="col-md-3 col-sm-6 col-xs-6 text-muted sep-small">
                  <a href="mailto:biuro@jemlokalnie.org">biuro@jemlokalnie.org</a>
              </div>
                <div class="col-md-3 col-sm-6 col-xs-6 text-muted sep-small">
                    <!--a href="https://facebook.com/jemlokalnieorg" target="_blank"><i class="fa fa-facebook" style="font-size: 22px;" aria-hidden="true"></i--><div class="min-logo"></div>
                </div>
              <br><br>
          </div>
      </footer>
    {% block modal %}{% endblock modal %}
  <script type="text/javascript">
    imageMapResize();
  </script>
  </body>
</html>
 